name: SpaceInvadersSaver

targets:
  SpaceInvadersSaver:
    type: bundle
    platform: macOS
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.drhugodabien.SpaceInvadersSaver
      WRAPPER_EXTENSION: saver
    sources:
      - path: Sources
      - path: Resources
        type: resources
    dependencies:
      - framework: ScreenSaver.framework
      - framework: WebKit.framework
    info:
      path: Info.plist
